### ISSUE TITLE
Version 1.13.2 isn't deployed to maven

### ISSUE THREAD

**Issue by Tofuus** [Exceptionflug/protocolize#1]
The latest version 1.13.2 doesn't appear to have been deployed to the maven repository https://i.imgur.com/UagJtiN.png

**Comment by Exceptionflug** [comment]
Hey, you can use version 1.13.1 or 1.13 since no api changes were made. Additionally I will deploy 1.13.2 right after I'm back home.

**Comment by Exceptionflug** [comment]
I've just deployed 1.3.2 to the maven repository :)
