### ISSUE TITLE
Using ItemStack#deepClone() gives a WARNING: {item} cannot be used on protocol version 756

### ISSUE THREAD

**Issue by 0ddlyoko** [Exceptionflug/protocolize#102]
As we can't clone an ItemStack, if we use `ItemStack#deepClone()` on an ItemStack, it gives a SEVERE error:

```
20:32:16 [SEVERE] oct. 25, 2021 8:32:16 PM dev.simplix.protocolize.api.item.ItemStackSerializer write
WARNING: RED_STAINED_GLASS_PANE cannot be used on protocol version 756.
```
I've tested with ItemStack.RED_STAINED_GLASS_PANE and ItemStack.STONE
 
After searching, it looks like `ItemStack#deepClone()` [call](https://github.com/Exceptionflug/protocolize/blob/6324cd3ffdf8567eb654600487487454c7cd3c28/protocolize-api/src/main/java/dev/simplix/protocolize/api/item/ItemStack.java#L162) `ItemStackSerializer#write(ByteBuf, ItemStack, int)` and the called method doesn't find the item at line `mapping = (ProtocolIdMapping)MAPPING_PROVIDER.mapping(stack.itemType(), protocolVersion);`.
Maybe the mapping is done later ?
(It worked in Protocolize v1)

![image](https://user-images.githubusercontent.com/11074473/138754752-1b9e7af2-e697-4bcf-be50-4928f43e09cf.png)

Update:
I clone items from the onEnable() method

**Comment by Exceptionflug** [comment]
Hey,

yes as you already stated, the mappings will be registered during onEnable. So it's not possible to clone items before that is done.
