### ISSUE TITLE
Geyser Floodgate Prefix BUG

### ISSUE THREAD

**Issue by OverBrave** [Exceptionflug/protocolize#103]
Working with GeyserMC, the Floodgate plugin adds a "." or puts a mark to front of **BEDROCK** player nickname, like prefix. 

But **"Protocolize"** prevents this.

I tested on Velocity. Jenkins build # 73

**Comment by KotlinFactory** [comment]
Hey OverBrave,

as discussed on Discord we will do our best to have this resolved as soon as possible.

Regards,
Leonhard

**Comment by Exceptionflug** [comment]
Issue resolved
