### ISSUE TITLE
Protocolize Error?

### ISSUE THREAD

**Issue by Brickwrath** [Exceptionflug/protocolize#104]
Hopefully this is helpful/meaningful to you, but as of the latest Protocolize version I'm getting this error occasionally in console:
`[dev.simplix.protocolize.data.packets.ClickWindow]: Unsupported click type with mode 0 and button 4! Protocol 756`

No clue what it means, and it doesn't seem to affect anything in-game.
Seems to be an inventory interaction, but I have no clue what's triggering it.
Sorry I couldn't shed more light on it, but like I said; hope it helps.

**Comment by CharlyZest** [comment]
Hello!
I have a similar error, but in my case it says:

`[dev.simplix.protocolize.data.packets.NamedSoundEffect]: Don't know what sound ambient.cave at protocol 754 should be.`
`[dev.simplix.protocolize.data.packets.NamedSoundEffect]: Don't know what sound block.anvil.hit at protocol 754 should be.`
`[dev.simplix.protocolize.data.packets.NamedSoundEffect]: Don't know what sound block.wood.step at protocol 756 should be.`

![image](https://user-images.githubusercontent.com/40046747/140830158-b3cb4337-cb11-4104-b395-b546f43e9a29.png)
![image](https://user-images.githubusercontent.com/40046747/140830269-8084c939-d9c1-4fa6-8302-439bd245d8cd.png)
![image](https://user-images.githubusercontent.com/40046747/140830316-c55fca79-651b-4711-9794-1815edec940a.png)

I think the affected class is `dev.simplix.protocolize.data.packets.NamedSoundEffect` and apparently it disconnects players to whom it should send the package when this error appears.
NOTE: These sound effects are NOT sent from any plugin that I have developed, the player gets them as their game progresses.

**Comment by Exceptionflug** [comment]
> 
> 
> Hello! I have a similar error, but in my case it says:
> 
> `[dev.simplix.protocolize.data.packets.NamedSoundEffect]: Don't know what sound ambient.cave at protocol 754 should be.` `[dev.simplix.protocolize.data.packets.NamedSoundEffect]: Don't know what sound block.anvil.hit at protocol 754 should be.` `[dev.simplix.protocolize.data.packets.NamedSoundEffect]: Don't know what sound block.wood.step at protocol 756 should be.`
> 
> ![image](https://user-images.githubusercontent.com/40046747/140830158-b3cb4337-cb11-4104-b395-b546f43e9a29.png) ![image](https://user-images.githubusercontent.com/40046747/140830269-8084c939-d9c1-4fa6-8302-439bd245d8cd.png) ![image](https://user-images.githubusercontent.com/40046747/140830316-c55fca79-651b-4711-9794-1815edec940a.png)
> 
> I think the affected class is `dev.simplix.protocolize.data.packets.NamedSoundEffect` and apparently it disconnects players to whom it should send the package when this error appears. NOTE: These sound effects are NOT sent from any plugin that I have developed, the player gets them as their game progresses.
> 
> Version: ![image](https://user-images.githubusercontent.com/40046747/140833423-0a38ce06-9711-40dd-9c0f-ea8fea493ac0.png)

Hello, this is another problem. Please open a seperate issue.

**Comment by Exceptionflug** [comment]
> 
> 
> Hopefully this is helpful/meaningful to you, but as of the latest Protocolize version I'm getting this error occasionally in console: `[dev.simplix.protocolize.data.packets.ClickWindow]: Unsupported click type with mode 0 and button 4! Protocol 756`
> 
> No clue what it means, and it doesn't seem to affect anything in-game. Seems to be an inventory interaction, but I have no clue what's triggering it. Sorry I couldn't shed more light on it, but like I said; hope it helps.

Sorry for the late response. I cannot reproduce your problem. Are you using mods? The minecraft client should never send a mode 0 click with button 4.

**Comment by Exceptionflug** [comment]
Closed, since there is no reaction.
