### ISSUE TITLE
NamedSoundEffect Issue

### ISSUE THREAD

**Issue by CharlyZest** [Exceptionflug/protocolize#105]
Hello!

I have this problem on my bungee console

`[dev.simplix.protocolize.data.packets.NamedSoundEffect]: Don't know what sound ambient.cave at protocol 754 should be.`
`[dev.simplix.protocolize.data.packets.NamedSoundEffect]: Don't know what sound block.anvil.hit at protocol 754 should be.`
`[dev.simplix.protocolize.data.packets.NamedSoundEffect]: Don't know what sound block.wood.step at protocol 756 should be.`

![image](https://user-images.githubusercontent.com/40046747/140830158-b3cb4337-cb11-4104-b395-b546f43e9a29.png)
![image](https://user-images.githubusercontent.com/40046747/140830269-8084c939-d9c1-4fa6-8302-439bd245d8cd.png)
![image](https://user-images.githubusercontent.com/40046747/140830316-c55fca79-651b-4711-9794-1815edec940a.png)

I think the affected module is `dev.simplix.protocolize.data.packets.NamedSoundEffect` and apparently it disconnects players to whom it should send the package when this error appears.
NOTE: These sound effects are NOT sent from any add-on they have developed, the player gets them as the game progresses in a "vanilla" way.

Protocolize Version: 
![image](https://user-images.githubusercontent.com/40046747/140833423-0a38ce06-9711-40dd-9c0f-ea8fea493ac0.png)

**Comment by Finnlife** [comment]
I can confirm this issue. 
Client: 1.16.5
Bungeecord: Flamecord 0.6.0
Protocolize: 2.0.0:40
![image](https://user-images.githubusercontent.com/26007800/146656461-5ba81e53-e72b-4485-be45-1f27c542988a.png)

**Comment by Exceptionflug** [comment]
There is definetely an issue there. I will take a look.

**Comment by Exceptionflug** [comment]
You are using an outdated version of protocolize. Please update to the latest version: https://simplixsoft.com/protocolize
