### ISSUE TITLE
Items in inventory are in italics

### ISSUE THREAD

**Issue by 0ddlyoko** [Exceptionflug/protocolize#106]
When putting a name or a lore on an item using `ItemStack#displayName(String)` and `ItemStack#lore(List<>)`, the text is italic.
Adding §r or a color let the name in italic

![image](https://user-images.githubusercontent.com/11074473/141169532-1485a508-20ae-4af1-9f61-95d8ae416daa.png)

**Comment by Exceptionflug** [comment]
From our discord support:
![Image](https://img.exceptionflug.de/Discord_EmIHLS0mfF.png)
