### ISSUE TITLE
Cannot invoke "java.util.List.iterator()" because "this.loreJson" is null

### ISSUE THREAD

**Issue by MeowRay** [Exceptionflug/protocolize#110]
Protocolize version: 2.1.0
bungeecord version:  1.18

NPE may be thrown when calling method ItemStack.lore()

![image](https://user-images.githubusercontent.com/29674595/145665487-ff3e2a1b-57f5-44bb-87b8-d210f4081d56.png)

![image](https://user-images.githubusercontent.com/29674595/145665491-94637220-39fb-4973-845f-e9f00fde275b.png)

![image](https://user-images.githubusercontent.com/29674595/145665497-8814afa5-567c-4144-99f3-7761322cbd20.png)

**Comment by Exceptionflug** [comment]
Hey, loreJson should never be null. Can you check if you are setting your lore to null elsewhere in your plugin? I also will add a null check for the mutator method.

**Comment by Exceptionflug** [comment]
I've fixed a related issue which may help you out in this case. Please try to use: https://ci.exceptionflug.de/job/Protocolize2/122/artifact/protocolize-bungeecord/target/protocolize-bungeecord.jar
