### ISSUE TITLE
If the length of the username not match, the connection will be directly disconnected

### ISSUE THREAD

**Issue by MeowRay** [Exceptionflug/protocolize#111]
bungeecord: offline mode
username: Length greater than 16
![image](https://user-images.githubusercontent.com/29674595/146544783-46ebbabf-a234-498c-b1f0-f576a0e86cf6.png)
![image](https://user-images.githubusercontent.com/29674595/146544786-ba381b3e-7e38-402d-a13e-65f469541302.png)

**Comment by MeowRay** [comment]
![image](https://user-images.githubusercontent.com/29674595/146545484-f69e6056-f3ef-4e5b-a50a-1e3e2802ac5a.png)

One more question,
I added protocolize-legacy-data-shared and protocolize-legacy-bungeecord and still "Don't know what item 261 at protocol 47 should be."

**Comment by Exceptionflug** [comment]
Uhm? Minecraft usernames cannot be longer than 17 characters. This is not a protocolize issue. This is a bug check inside of BungeeCord.
