### ISSUE TITLE
Don't know what item XXX  at protocol XX should be

### ISSUE THREAD

**Issue by MeowRay** [Exceptionflug/protocolize#112]
Installed protocolize-bungeecord and protocolize-legacy-bungeecord
Items with durability are not visible in lower versions(test client: 1.8.9)

![image](https://user-images.githubusercontent.com/29674595/146644788-96b41a9c-1202-4724-9eb1-0b5b59102ef9.png)

bungeecord: 1.18
spigot: 1.8.8
protocolize: 2.10
client: 1.8.9

**Comment by Exceptionflug** [comment]
Hey, durability is not supported for items < 1.13

**Comment by MeowRay** [comment]
> Hey, durability is not supported for items < 1.13

Reproduce: https://github.com/Exceptionflug/protocolize/issues/49#issuecomment-687805594

**Comment by MeowRay** [comment]
> Hey, durability is not supported for items < 1.13

So will the modified item not be visible on the client of the lower version?

**Comment by Exceptionflug** [comment]
Don't know. Tell me.

**Comment by MeowRay** [comment]
> Don't know. Tell me.

Modified potion item is not visible in the lower version client and log print "Don't know what item XXX at protocol XX should be"
Same: https://github.com/Exceptionflug/protocolize/issues/49#issuecomment-687806790

![protocolize](https://user-images.githubusercontent.com/29674595/146667712-0de1413d-f3d3-4c9a-9628-2b9835283f9e.gif)

**Comment by Exceptionflug** [comment]
Probably won't add support for this, since this is a corner case and it only affects outdated versions of the game.
