### ISSUE TITLE
Right-click interaction of the high version client may be kicked out when using viaversion

### ISSUE THREAD

**Issue by MeowRay** [Exceptionflug/protocolize#113]
spigot: 1.8.8
bungeecord: 1.18
protocolize: 2.1.0
viaversion: 4.1.2
client: 1.18.1

Whenever spigot 1.8.8 is restarted, using the 1.18.1 client to join the game right-click may be kicked out, and you need to rejoin several times to right-click normally

![image](https://user-images.githubusercontent.com/29674595/147885553-397ac714-c1bc-41ab-bdda-e3e44aeb3655.png)
![image](https://user-images.githubusercontent.com/29674595/147885571-1ccce813-fa75-486c-b0d1-6ca615d5d465.png)

**Comment by Exceptionflug** [comment]
Hey, this issue should not accour. It may be the fault of ViaVersion creating invalid block placement packets. Can you try to reproduce this with an spigot 1.18.1 server? Protocolize is accepting block placement packets according to https://wiki.vg/Protocol#Player_Block_Placement

**Comment by Exceptionflug** [comment]
Does this still occur?

**Comment by MeowRay** [comment]
> Does this still occur?

2.1.1 seems to have fixed this

**Comment by Exceptionflug** [comment]
Legacy versions aren't supported anymore. So sorry for the wait. I guess it is a viaversion issue since the 1.8 implementation of Protocolize is nearly perfect and long time tested on a big mc network.

**Comment by Exceptionflug** [comment]
Closed due to inactivity
