### ISSUE TITLE
ClassCastException BaseComponent cannot be cast to class BaseComponent

### ISSUE THREAD

**Issue by HevelMc** [Exceptionflug/protocolize#114]
**Describe the bug**
Any bungeecord component cannot be used as display name and lores of items.

**To Reproduce**
```java
Inventory inventory = new Inventory(InventoryType.GENERIC_9X1);
ItemStack item = new ItemStack(ItemType.DIRT);
BaseComponent component = new TextComponent("TESTING");
item.displayName(component);
inventory.item(4, item);
```

I explicitly cast TextComponent to BaseComponent here, but the error occurred even without casting.

**Screenshots**
![image](https://user-images.githubusercontent.com/42890916/148678475-ca679843-e966-483c-a7d6-c2895ce9a509.png)

**Proxy environment**
Running on Waterfall version `1.18-R0.1-SNAPSHOT:adabf32:474`

**Minecraft version used**
Minecraft `1.18.1/vanilla`

**Comment by KotlinFactory** [comment]
Hey,

it looks like you are shading protocolize into your .jar. 
This will lead to issues like that.

The menu system of Protocolize is tested and runs fine if used properly, for example, see [Cirrus](https://github.com/Simplix-Softworks/Cirrus).

Please reopen if it still occurs.


Regards,
Leonhard
