### ISSUE TITLE
Velocity proxy server crash

### ISSUE THREAD

**Issue by ilfarpro** [Exceptionflug/protocolize#115]
**Describe the bug**
Can't describe what happened. I just joined server and it's crashed. 
Maybe it's because I run 2 instances of the same proxy server on different IPs?

**To Reproduce**
Can't reproduce.

**Logs**
18.01 00:43:35 [Server] INFO [server connection] KindHeart -> survival has connected
18.01 00:45:02 [Server] ERROR [dev.simplix.protocolize.velocity.listener.PlayerListener]: Pipeline is not initialized. This is a bug. Please report. Pipeline handlers = {}
18.01 00:45:02 [Server] ERROR [dev.simplix.protocolize.velocity.listener.PlayerListener]: Initializer: dev.simplix.protocolize.velocity.netty.ProtocolizeBackendChannelInitializer
18.01 00:45:08 [Server] ERROR [dev.simplix.protocolize.velocity.listener.PlayerListener]: Pipeline is not initialized. This is a bug. Please report. Pipeline handlers = {}
18.01 00:45:08 [Server] ERROR [dev.simplix.protocolize.velocity.listener.PlayerListener]: Initializer: dev.simplix.protocolize.velocity.netty.ProtocolizeBackendChannelInitializer
18.01 00:45:10 [Server] ERROR [dev.simplix.protocolize.velocity.listener.PlayerListener]: Pipeline is not initialized. This is a bug. Please report. Pipeline handlers = {}
18.01 00:45:10 [Server] ERROR [dev.simplix.protocolize.velocity.listener.PlayerListener]: Initializer: dev.simplix.protocolize.velocity.netty.ProtocolizeBackendChannelInitializer
18.01 00:45:29 [Server] ERROR [dev.simplix.protocolize.velocity.listener.PlayerListener]: Pipeline is not initialized. This is a bug. Please report. Pipeline handlers = {}
18.01 00:45:29 [Server] ERROR [dev.simplix.protocolize.velocity.listener.PlayerListener]: Initializer: dev.simplix.protocolize.velocity.netty.ProtocolizeBackendChannelInitializer
18.01 00:45:36 [Server] ERROR [dev.simplix.protocolize.velocity.listener.PlayerListener]: Pipeline is not initialized. This is a bug. Please report. Pipeline handlers = {}
18.01 00:45:36 [Server] ERROR [dev.simplix.protocolize.velocity.listener.PlayerListener]: Initializer: dev.simplix.protocolize.velocity.netty.ProtocolizeBackendChannelInitializer

**Proxy environment**
Velocity 3.1.1-98
Plugins:
![image](https://user-images.githubusercontent.com/16963651/149852867-1b12b48d-eccc-4326-a727-5e0a4dff1e12.png)

**Minecraft versions used**
1.18.1 fabric

**Comment by Exceptionflug** [comment]
Hey, sadly we are encounter some issues when using TCPShield. There is currently no ETA when a solution to this issue is available. Maybe this issue can't be fixed since we have not access to a platform running with TCPShield to develop on.

**Comment by Ytnoos** [comment]
Having this problem too with TCPShield (their source is public)

**Comment by Teyir** [comment]
Hello,

I have the same issue

**Comment by Teyir** [comment]
And this is the error

`=>.... [10:14:04 ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: Pipeline is not initialized. This is a bug. Please report. Pipeline handlers = {}
>.... [10:14:04 ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: Initializer: dev.simplix.protocolize.velocity.netty.ProtocolizeBackendChannelInitializer
>.... [10:15:04 ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: Unable to initialize InboundConnection on ping
java.lang.NullPointerException: null
at dev.simplix.protocolize.velocity.listener.PlayerListener.initConnection(PlayerListener.java:119) ~[?:?]
at dev.simplix.protocolize.velocity.listener.PlayerListener.onPing(PlayerListener.java:62) ~[?:?]
at dev.simplix.protocolize.velocity.listener.Lmbda$25.execute(Unknown Source) ~[?:?]
at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[server.jar:3.1.2-SNAPSHOT (git-7bd0f9ea-b114)]
at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.1.2-SNAPSHOT (git-7bd0f9ea-b114)]
at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.1.2-SNAPSHOT (git-7bd0f9ea-b114)]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
at java.lang.Thread.run(Thread.java:829) [?:?]`

**Comment by Teyir** [comment]
Hello @Exceptionflug what do you need for test / try to fix this bug ?

**Comment by OverBrave** [comment]
> Hey, sadly we encounter some issues when using TCPShield. There is currently no ETA when a solution to this issue is available. Maybe this issue can't be fixed since we have not access to a platform running with TCPShield to develop on.

So, i don't use TCPShield but i have same problem. Could something else be causing it? Geyser, Query connections or something.

**Comment by Exceptionflug** [comment]
Yeah it could also be Geyser

**Comment by Exceptionflug** [comment]
> Hello @Exceptionflug what do you need for test / try to fix this bug ?

I need a fully working TCPShield environment.

**Comment by PedroMPagani** [comment]
Has this been continued?

**Comment by KotlinFactory** [comment]
Hi is this still a problem?

**Comment by PedroMPagani** [comment]
> Hi is this still a problem?

I have not seen crashes on my env, we are full tcpshield and we have 700 avg players, I would guess it isn't.

**Comment by KotlinFactory** [comment]
Closing this. If you encounter this, feel free to drop a message here and we will reopen it.

**Comment by mallusrgreatv2** [comment]
Having this issue on TCPShield

**Comment by SolarPepper** [comment]
I am not using TCPShield, but I am getting this error
Velocity 

````[07:24:26] [Velocity Async Event Executor - #0/ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: Pipeline is not initialized. This is a bug. Please report. Pipeline handlers = {}
[07:24:26] [Velocity Async Event Executor - #0/ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: Initializer: dev.simplix.protocolize.velocity.netty.ProtocolizeBackendChannelInitializer````
