### ISSUE TITLE
TabCompleteResponse start always returns 0 on velocity

### ISSUE THREAD

**Issue by TauCubed** [Exceptionflug/protocolize#120]
**Describe the bug**
when trying to read the start position of a TabCompleteResponse return 0 when the connected client is using a version below 1.13

**To Reproduce**
1. Steps to reproduce the behavior:
2. Create a Velocity proxy instance running both ViaVersion and ViaBackwards
3. Create a UPSTREAM listener for TabCompleteResponse packets that will print the start position of the Tab-Complete
4. Join the proxy with a version below 1.13
5. Try to tab-complete a command such as `/msg <first letter of your username>`
6. Observe results

**Expected behavior**
start position to be filled with the correct information.

**Screenshots**

**Proxy environment**
Velocity proxy, ViaVersion, ViaBackwards and my plugin trying to read these values.

**Minecraft versions used**
Destination server running Paper-1.18.2
Client running 1.12.2 (anything below 1.13 seems to cause this issue)

If you think this might be a ViaVersion issue [I did create an issue there](https://github.com/ViaVersion/ViaBackwards/issues/447) but they said it It wasn't a VIA issue.
As described in that issue the transactionId isn't returning the correct value either, as for clients below 1.13 It's supposed to be a random value generated by VIA.

**Some other info**
On bungeecord (with ViaVersion, ViaBackwards and a 1.12.2 client) the start position of the suggestions returns the correct value.

Thank you.

**Comment by Exceptionflug** [comment]
Hello, thank you for your interest.

Since the TabCompleteResponse packet is implemented by Velocity themselves I suggest opening an issue on their end. Protocolize is just feeding the packet class with binary data, so we don't have an impact on how the packet is being deserialized.

**Comment by TauCubed** [comment]
Thank you.
I'll inquire over there about this issue.
