### ISSUE TITLE
heldItem use

### ISSUE THREAD

**Issue by leChapelierFou-D** [Exceptionflug/protocolize#121]
How use set heldItem in PlayerInventory? because I need to update this value, not forcing to player his held or resend to server and player anytime the player change.

**Comment by Exceptionflug** [comment]
I guess you are trying to set the slot of the current held item?
`PlayerInventory#heldItem(short slot)` does this for you. It informs the server that the client has switched the held item slot and the client will be forced to also switch the held item slot. Changing this value without informing the client and server makes no sense and would cause inconsistancy in inventory tracking.

**Comment by Exceptionflug** [comment]
Closed due to inactivity
