### ISSUE TITLE
I have a hopefully simple question

### ISSUE THREAD

**Issue by PrismoidNW** [Exceptionflug/protocolize#124]
Hello everyone,
I am running velocity (current version) as well as a 1.8.8 PaperMC server connected to the proxy. I am wondering if the minimum tested version, which is 1.13, is talking about the velocity version, or the client/server versions. I would like to know if I would be able to use this as to create menus and send them to 1.8 players. Thanks.

- Prismoid

**Comment by Exceptionflug** [comment]
Hello,

the meant versions are the ones of the connected clients. You can add aditional 1.8 support by installing the legacy module for your platform.

**Comment by PrismoidNW** [comment]
Alright, thanks
