### ISSUE TITLE
Issue with item stacks

### ISSUE THREAD

**Issue by LaserSlime** [Exceptionflug/protocolize#126]
**Describe the bug**
The display name and lore of item stacks is always italic. Even when putting a §r at the beginning of the string. The only way to prevent this is to use components, which is very inconvenient. Also the methods to modify the lore don't return the item stack like all the other ItemStack methods.

**To Reproduce**
1. Create an itemstack.
2. Add a lore or display name starting with "§r" to it.
3. Put it in a gui and show it to the player.
4. See how the text is still italic despite being reset.

**Expected behavior**
Putting §r at the beginning should make the text non italic.

**Proxy environment**
git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483

**Minecraft versions used**
Client version 1.17.1

**Comment by Exceptionflug** [comment]
This is a client side behaviour. Custom item names are always shwon in italic (e.g. when renaming an item with an anvil). The only possibility to suppress this is by explicitly set the italic property of the component to false. The §r is not achieving this goal.

**Comment by LaserSlime** [comment]
But i'm very sure putting §r at the beginning works with bukkit itemstacks.

**Comment by Exceptionflug** [comment]
If it works, then this is custom implemented behaviour on the bukkit end.

**Comment by KotlinFactory** [comment]
Hi this actually seems to be an issue, I will look into this.

**Comment by remazil** [comment]
UP

**Comment by remazil** [comment]
Check how it been fixed in [https://github.com/tritonmc/Triton/commit/974426fc4251572da360de7f02419b1fc7bbd80a](https://github.com/tritonmc/Triton/commit/974426fc4251572da360de7f02419b1fc7bbd80a)

**Comment by Exceptionflug** [comment]
This is finally fixed with Protocolize v2.3.3. Thank you for you patience.
