### ISSUE TITLE
Opened inventory isn't updated after change

### ISSUE THREAD

**Issue by LaserSlime** [Exceptionflug/protocolize#127]
**Describe the bug**
When creating an inventory, opening it and then changing items afterwards the inventory is not updated until you click anywhere and there is no method provided to manually refresh it.

**To Reproduce**
1. Create an inventory
2. Show it to a player
3. Add an item
4. The item won't be shown until you click anywhere in the inventory to update it

**Expected behavior**
There should be a method like Inventory#update() similar to the one that exists in PlayerInventory.

**Proxy environment**
git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483

**Minecraft versions used**
Client version 1.17.1

**Comment by Exceptionflug** [comment]
Hey, the way to go is to call the ProtocolizePlayer#openInventory method again for that already opened inventory. Protocolize knows that and resends the inventory contents to the player.

**Comment by LaserSlime** [comment]
> Hey, the way to go is to call the ProtocolizePlayer#openInventory method again for that already opened inventory. Protocolize knows that and resends the inventory contents to the player.

The contents aren't resent. It just opens a new inventory which has two main down sides:
1. The cursor position gets reset.
2. There's no way to check if the inventory has been closed (apart from the onClose method i guess, but that's very inconvenient) and if it's closed, it will open again.

**Comment by Exceptionflug** [comment]
Then there is something wrong. You can check ProtocolizePlayer#registeredInventories to check if there is an registered inventory after opening it.

**Comment by LaserSlime** [comment]
Well I just printed out all the keys and values of ProtocolizePlayer#registeredInventories whenever I opened the inventory and this was the result:

```
[19:58:15 INFO]: 102 dev.simplix.protocolize.api.inventory.Inventory@cbe2f84
[19:58:15 INFO]: 102 dev.simplix.protocolize.api.inventory.Inventory@d17d970a
[19:58:15 INFO]: 102 dev.simplix.protocolize.api.inventory.Inventory@c40e0ec2
[19:58:15 INFO]: 102 dev.simplix.protocolize.api.inventory.Inventory@f97e8a16
```

For some reason it seems to create a new inventory each time, which replaces the old one.

**Comment by Exceptionflug** [comment]
Are you passing the same instance of `dev.simplix.protocolize.api.inventory.Inventory` to `ProtocolizePlayer#openInventory` all times? Protocolize does an instance check against the already registered inventories to see if they are the same.

**Comment by LaserSlime** [comment]
Oh so i have to save every instance per player?

**Comment by Exceptionflug** [comment]
Yes

**Comment by KotlinFactory** [comment]
I will close this, if there are still issues regarding this we will reopen this.
