### ISSUE TITLE
Pipeline is not initialized BUG

### ISSUE THREAD

**Issue by editon96** [Exceptionflug/protocolize#128]
**Describe the bug**
I configure Velocity and the bug arrives.

**Expected behavior**
In the Conole that are be spammed:

[11:40:24 ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: Pipeline is not initialized. This is a bug. Please report. Pipeline handlers = {}
[11:40:24 ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: Initializer: dev.simplix.protocolize.velocity.netty.ProtocolizeBackendChannelInitializer

**Proxy environment**
I run Velocity 3.1.2 Snapshoot 140
Plugins i am Running:
- botsentery
- floodgate
- Geyser-Velocity
- Geyser Updater
- luckyperms
- nuvotifer
- party and frends
- serverGUI
- SlashServer
- VerlocityControl - Chat Control Red for Velocity
- Voting Plugin
- snap:
  - AdvancedNModt
  - ath
  - clans for Party and Frends
  - CMIB
  - PAFFloodgate Extension
  - TAB
  - UltraEconomy
  - UltraModt
  - UltraPunishments

**Comment by editon96** [comment]
https://pastebin.com/JTWwSCZS - LOG

**Comment by KotlinFactory** [comment]
Don't use floodgate & Geyser-Velocity

**Comment by editon96** [comment]
But if I dont use both Bedrock Player cant connect

**Comment by Exceptionflug** [comment]
> Don't use floodgate & Geyser-Velocity

Correct. Just put a dedicated Geyser proxy in front of your velocity proxy like in the old days.
