### ISSUE TITLE
General 1.19 incompatibility

### ISSUE THREAD

**Issue by CodfishBender** [Exceptionflug/protocolize#130]
**Console Error**
```
19:02:19 [INFO] [Eroserv,/127.0.0.1:1204] <-> InitialHandler has connected
19:02:19 [INFO] [Eroserv] <-> ServerConnector [hub] has connected
19:02:19 [WARNING] [Eroserv] <-> DownstreamBridge <-> [hub] - bad packet, are mods in use!? Packet GAME:TO_CLIENT/21 (GeneratedWindowPropertyWrapper) larger than expected, extra bytes: 17
19:02:19 [INFO] [Eroserv] disconnected with: DecoderException : net.md_5.bungee.protocol.BadPacketException: Packet GAME:TO_CLIENT/21 (GeneratedWindowPropertyWrapper) larger than expected, extra bytes: 17 @ io.netty.handler.codec.MessageToMessageDecoder:98
19:02:19 [INFO] [Eroserv] -> UpstreamBridge has disconnected
19:02:19 [INFO] [Eroserv] <-> DownstreamBridge <-> [hub] has disconnected
```

**Bug Description**
Players with 1.19 clients are unable to join while Protocolize is on the 1.19 proxy and ViaVersions is on the 1.18.2 server.
Removing Protocolize from the proxy solves the issue.

**Proxy**: BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT
**Proxy Plugin**: Protocolize version 2.2.0:315 by Exceptionflug

**Server**: git-Paper-283 (MC: 1.18.2)
**Server Plugin**: ViaVersion v4.3.2-SNAPSHOT

**Steps to Reproduce**
1. Create a 1.19 BungeeCord proxy that connects to a single 1.18.2 Paper server.
2. Use Protocolize version 2.2.0 plugin with the 1.19 BungeeCord proxy.
3. Use ViaVersion 4.3.2-SNAPSHOT plugin with the 1.18.2 Paper server.
4. Start the BungeeCord proxy.
5. Start the Paper server.
6. Attempt to connect to the proxy and it will display the error.

**Expected Behavior**
The player should be able to connect to the network without any error message.

**Additional Info**
This was occurred on my live network and I was able to reproduce the issue on my local machine with the 2 plugins. I have posted this to the ViaVersions git page as well, as I'm unsure what is prompting this error.

**Comment by Exceptionflug** [comment]
Hello, it seems like there was a major lack of protocol documentation when updating to 1.19. I will fix this when I've got time.

**Comment by Exceptionflug** [comment]
Released https://github.com/Exceptionflug/protocolize/releases/tag/v2.2.1 which fixes the mentioned issues. Sorry for the inconvenience.
