### ISSUE TITLE
Player gets kicked when try to trade with villagers

### ISSUE THREAD

**Issue by Kay313** [Exceptionflug/protocolize#139]
**Describe the bug**
If protocolize is on on the Velocity server and then you try to trade through any sub-server with a villager, you will be kicked.

**To Reproduce**
1. Add protocolize on a Velocity Server
2. Join a sub-server
3. Try to trade with a villager
4. View the error in the Velocity Console and protocolize Log

**Proxy environment**
velocity-3.1.2-SNAPSHOT-158
https://paste.gg/p/anonymous/88452844dcc64bc5980cd9743612b6ec

**Minecraft versions used**
1.19

Error Log:
Velocity Log:
https://paste.gg/p/anonymous/507ac7abc371405cb11b145f951630c4 

protocolize Log:
https://paste.gg/p/anonymous/4b1526d27ce246adb777f3e033c9201a

**Comment by Pantera07** [comment]
https://simplixsoft.com/protocolize
Use the latest version.

**Comment by Kay313** [comment]
it works with the latest version, thanks
