### ISSUE TITLE
HexaCord support

### ISSUE THREAD

**Issue by Ushust** [Exceptionflug/protocolize#143]
I use GuardHexa (a fork of HexaCord and also the best proxy core of minecraft), like many others, I saw how they turned to discord for help, but did not help. Can you make HexaCord support? I ask you very much, thank you in advance. I can pay if I have to.

Sincerely Ushust 🙂

**Comment by KotlinFactory** [comment]
Hi,

we don't support any shady third party forks. Its great that you would like to pay us. But whilst working with protocolize v1 we found that adding support for forks that alter packet behavior was greatly painful and started to inflict damage to the codebase. We also strongly recommend you sticking with BungeeCord/Waterfall/Velocity. This is also the software that big networks make use of.
We wish you best of luck with your network.

Regards,
Leonhard
