### ISSUE TITLE
Console error with FlameCord

### ISSUE THREAD

**Issue by NoltoxGit** [Exceptionflug/protocolize#151]
**Describe the bug**
With the latest version of Protocolize, when I try to connect 1.19.1 there is a huge error packet that spams the console.

**To Reproduce**
1. Go to `https://simplixsoft.com/protocolize`
2. Click on ` Protocolize for BungeeCord `
3. Launch server with `java -Xms128M -Xmx3072M -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15 -jar FlameCord_106.jar --nogui`

**Logs:**
https://pastebin.com/X3nfD8Nb

**Proxy environment**
Latest version of FlameCord 1.0.6.

**Minecraft versions used**
Minecraft client: Fabric 1.19.1
Minecraft server: Latest Purpur 1.19.1 (#1748)

**Comment by LuluxClient** [comment]
I have the same issue: https://pastebin.com/myk8Tryz

**Comment by Pantera07** [comment]
Try again with the latest version.

Download latest version: https://simplixsoft.com/protocolize

**Comment by NoltoxGit** [comment]
Hellow,
The problem seems to be solved, thx u very much!
