### ISSUE TITLE
Can't join on 1.19.1

### ISSUE THREAD

**Issue by SwartZCoding** [Exceptionflug/protocolize#152]
**Describe the bug**
When i join my server, i got this issue and it's impossible to login : https://gyazo.com/547cecc4769c89ae9eba892ab349c2ae

**To Reproduce**
1. Download this version https://github.com/Exceptionflug/protocolize/releases/tag/v2.2.2 (Bungeecord)
2. Start your bungeecord with this version. (I use Flamecord on latest (1.0.6)).
3. Try to join. And you got this issue.

**Expected behavior**
Just join my server lol :).

**Screenshots**

**Proxy environment**
Bungeecord : Flamecord on latest 1.0.6 version.
Plugins : AdvancedNMotd, BungeePackFix, Liteban, Luckperms, Protocolize, Tab.

**Minecraft versions used**
Latest Minecraft 1.19.1 with latest purpur 1.19.1

**Comment by Pantera07** [comment]
https://github.com/Exceptionflug/protocolize/issues/150

**Comment by Pantera07** [comment]
Download latest version: https://simplixsoft.com/protocolize

**Comment by Exceptionflug** [comment]
Btw Flamecord is not officially supported

**Comment by KotlinFactory** [comment]
I will close this. If there is still an issue regarding this, feel free to post here and we will reopen this.
