### ISSUE TITLE
Velocity pipeline bug

### ISSUE THREAD

**Issue by AceSardonyx** [Exceptionflug/protocolize#154]
The bug occurs when velocity joins a player with protocolize.
It only seems to do it with bedrock players because I have no tested java players.
Seeing as there is another issue regarding this, I'll say that it does happen with java players.
Just creating this to push the attention.

1. Add protocolize
2. Boom, pipeline errors
Expected: Player can connect smoothly without being kicked.

I have tested it with and without plugins. Same error.

Latest Velocity version as of this time.
1.19 Native but via vrb are also being used

Here's a log: [latest.log](https://github.com/Exceptionflug/protocolize/files/9282795/latest.log) 
I am using protocolize-velocity.jar and protocolize-legacy-velocity.jar

**Comment by Exceptionflug** [comment]
Hello,

sorry for the late response but Protocolize is not compatible with Geyser atm.
