### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by kyngs** [Exceptionflug/protocolize#155]
**Describe the bug**
When doing this:
```java
        var item = new ItemStack(
                ItemType.FILLED_MAP,
                1,
                (short) 0
        );
                protocolize.sendPacket(
                new SetSlot()
                        .slot((short) 36)
                        .itemStack(item)
        );
```

I get the following exception
`java.lang.NoSuchMethodError: 'dev.simplix.protocolize.data.packets.SetSlot dev.simplix.protocolize.data.packets.SetSlot.itemStack(dev.simplix.protocolize.api.item.ItemStack)'`
I am using the latest API as my dependency.

**To Reproduce**
Described above ^

**Expected behavior**
It just should work

**Screenshots**
Not applicable

**Proxy environment**
Not applicable

**Minecraft versions used**
Not applicable

**FIX**
I suppose that this could be fixed by upgrading the data module to 2.2.2, and not using the old one (2.2.1)

**Comment by KotlinFactory** [comment]
Should be fixed already.
If not send a message in here and I will reopen this.

**Comment by KotlinFactory** [comment]
Should be fixed already.
If not send a message in here and I will reopen this.
