### ISSUE TITLE
Text response from anvil

### ISSUE THREAD

**Issue by KoopinSmall** [Exceptionflug/protocolize#157]
Hello, is there any way to get the entered string into the gui anvil that was created via Protocolize?

**Comment by KoopinSmall** [comment]
@Exceptionflug

**Comment by KoopinSmall** [comment]
@KotlinFactory

**Comment by KoopinSmall** [comment]
@Pantera07

**Comment by Exceptionflug** [comment]
Hello,

sorry for the late reply. Yes this is possible but you have to implement packet https://wiki.vg/Protocol#Rename_Item on your own.
