### ISSUE TITLE
console errorr

### ISSUE THREAD

**Issue by haroldrc** [Exceptionflug/protocolize#158]
**Describe the bug**
https://pastebin.com/yzFwncxN

**Minecraft versions used**
minecraft client: 1.18.2
server version : 1.17
bungee ver: FlameCord version 1.0.6 by

**Comment by editon96** [comment]
Same here https://pastebin.com/yT8pAuXc

Minecraft Versions:
Proxy: Velocity 3.2.1 Build 179
Server: Purpur 1.19.2 Build 1770

**Comment by KotlinFactory** [comment]
The method you are using has been removed.
This is not a bug.

Regards,
Leonhard
