### ISSUE TITLE
Invsee by EssentialsX (and other plugins too) doesn't work.

### ISSUE THREAD

**Issue by Fredh1000** [Exceptionflug/protocolize#159]
**Describe the bug**
I cannot use essentials / invsee (player), I will get an error on the proxy console.

**To Reproduce**
1. install a server 1.8.8 and put essentialsx on it.
2. Put velocity as proxy and add protocolize + legacy module.
3. enter the server with 2 accounts, oppose with one of the two accounts and do / invsee (other account)
4. invsee will not work and you will see error in proxy console.

**Expected behavior**
I expected invsee to work properly and allow me to see other people's inventory.

**Screenshots**
![Screenshot (232)](https://user-images.githubusercontent.com/82319919/188673287-4063b19f-883a-4637-900c-df8cc9c7ac7e.png)

**Proxy environment**
Proxy: I'm using Velocity build # 179.

**Minecraft versions used**
Server version: Paper 1.8.8

**Comment by GEOEGII555** [comment]
Protocolize v2 does not supports this version as it's too old

**Comment by Exceptionflug** [comment]
It seems like you are using an outdated protocolize version. Try again using the latest version and then send the stacktrace again.

**Comment by CoachYT1** [comment]
I'm using latest dev build and this is the stacktrace: https://pastebin.com/Qx8PCcix
