### ISSUE TITLE
Inventory Bug

### ISSUE THREAD

**Issue by ImRetroo** [Exceptionflug/protocolize#16]
When you open an inventory and then you close, the player inventory disappear and there is a warn in the console:

[18:58:54 WARN]: [Protocolize] ImRetroo_ has no open inventory with id 123

My minecraft version is 1.8.8 
Thanks and sorry for my english!

**Comment by JavaFactoryDev** [comment]
I chinese too

**Comment by Exceptionflug** [comment]
Hello,

thank you for your interest. It would be nice if you could provide more details about the inventory you have opened.

**Comment by ImRetroo** [comment]
When you open an inventory, and you click your own inventory the item that you click disappear for no reason!

**Comment by Exceptionflug** [comment]
'An inventory' is quite unexact. I need to know WHICH inventory you exactly have opened in order to begin with reproducing.

**Comment by ImRetroo** [comment]
`MenuHandler menu = new MenuHandler(InventoryType.GENERIC_9X6, "Prueba", PaginatedGUI.PageFormat.TWO_ROWS, null);
->
        this.size = size;
        this.title = title;
        this.format = format.getFormat();
        this.indicator = indicator;
        this.inventory = new Inventory(this.size, new TextComponent(title));
        if(indicator != null) setIcon(size.getTypicalSize(Protocol.version) - 5, new Icon(indicator));
        index = 0;
        Main.inventory.put(inventory.getTitle().toString(), this);
`

**Comment by ImRetroo** [comment]
```
MenuHandler menu = new MenuHandler(InventoryType.GENERIC_9X6, "Prueba", PaginatedGUI.PageFormat.TWO_ROWS, null);
-------------------
        this.size = size;
        this.title = title;
        this.format = format.getFormat();
        this.indicator = indicator;
        this.inventory = new Inventory(this.size, new TextComponent(title));
        if(indicator != null) setIcon(size.getTypicalSize(Protocol.version) - 5, new Icon(indicator));
        index = 0;
        Main.inventory.put(inventory.getTitle().toString(), this);
```

**Comment by Exceptionflug** [comment]
How do you open the inventory?

**Comment by ImRetroo** [comment]
```
MenuHandler menu = new MenuHandler(InventoryType.GENERIC_9X6, "Prueba", PaginatedGUI.PageFormat.TWO_ROWS, null);
                Icon icon = new Icon(new ItemBuilder(ItemType.ARROW).setName("DIOS").toItemStack());
                icon.addClickAction(new ClickAction() {
                    @Override
                    public void execute(ProxiedPlayer player, ClickType type) {
                        player.sendMessage(ChatColor.translateAlternateColorCodes('&', "&a&lPRUEBA XD"));
                        InventoryModule.closeAllInventories(player);
                    }
                });
                menu.addItem(icon);
                InventoryModule.sendInventory(player, menu.getInventory());
```

**Comment by Exceptionflug** [comment]
Do you have the experimental features enabled by setting their value to true in the config file?

**Comment by ImRetroo** [comment]
No

**Comment by JavaFactoryDev** [comment]
I'm a flying sheep

**Comment by Exceptionflug** [comment]
Okay. Are you able to publish your code on github?

**Comment by ImRetroo** [comment]
Yep, give me a minutes

**Comment by ImRetroo** [comment]
Ok, I invited you to my repository, accept the invite please

**Comment by Exceptionflug** [comment]
I will take a look at this tomorrow :)

**Comment by ImRetroo** [comment]
Thanks

**Comment by ImRetroo** [comment]
Hey! Have you been able to look at the code?

**Comment by Exceptionflug** [comment]
Yes I've already taken a look. I cannot see any problems at all. You can try to take a look at the [MCCommons inventory listener](https://github.com/Exceptionflug/mccommons/blob/master/mccommons-inventories/mccommons-inventories-proxy/src/main/java/de/exceptionflug/mccommons/inventories/proxy/listener/InventoryListener.java) to check your code.

**Comment by ImRetroo** [comment]
Why is this happen?
[https://i.gyazo.com/ca4be7f77bf9a5d3f66c0647ed0fd00c.mp4](url)

**Comment by ImRetroo** [comment]
Why is this happen?
[https://i.gyazo.com/ca4be7f77bf9a5d3f66c0647ed0fd00c.mp4](https://i.gyazo.com/ca4be7f77bf9a5d3f66c0647ed0fd00c.mp4)

**Comment by Exceptionflug** [comment]
This is happening because protocolize is not knowing the items in your lower inventory singe these are sent by spigot. You can try to not cancel the event if you click in the lower inventory.

**Comment by ImRetroo** [comment]
> This is happening because protocolize is not knowing the items in your lower inventory since these are sent by spigot. You can try to not cancel the event if you click in the lower inventory.

At the moment, i dont have any line that cancel the InventoryClickEvent and still happens the same...

**Comment by Exceptionflug** [comment]
I cannot reproduce this problem. Please ensure that you are using the latest bungeecord version and java 8.

**Comment by Exceptionflug** [comment]
Okay I reproduced this problem. As stated above, protocolize is currently not able to fix this problem since protocolize cannot know which item lies on that slot to re-place it after the click.
