### ISSUE TITLE
1.19.3 bungee issue

### ISSUE THREAD

**Issue by EndermanPvP** [Exceptionflug/protocolize#168]
**Describe the bug**
Throws a giant log making reading logs unreadable when trying to look at history
Also lets players hide the commands they executed eg: staff bans a member that wasnt meant to be banned or does something they shouldn't do.

**To Reproduce**
1. Join a bungeecord server with the latest bungee/waterfall version (Using waterfall as a preference)
2. Enter `/` in chat and look at console

**Expected behavior**
Will throw a ugly, giant piece of text in console making logs unreadable.
Console logs: https://pastebin.com/raw/LqUAC0FU

**Screenshots**
*Nothing needed.*

**Proxy environment**
Pl-Hide-Pro

**Minecraft versions used**
Waterfall (510)

**Comment by EndermanPvP** [comment]
also there are other plugins but none use this

**Comment by EndermanPvP** [comment]
also (ik i said also again) 1.19.3 players cannot connect

**Comment by Exceptionflug** [comment]
Hey,

this issue should be resolved with the latest build. You can download it here:
https://ci.exceptionflug.de/job/Protocolize2/

thanks for your patience.
