### ISSUE TITLE
Packet listening bug

### ISSUE THREAD

**Issue by VladMartyshev** [Exceptionflug/protocolize#17]
```
public class HandshakePacketListener extends PacketAdapter<Handshake> {  
 
  public HandshakePacketListener() {
	  super(Stream.DOWNSTREAM, Handshake.class);
	}

  @Override  
  public void send(PacketSendEvent<Handshake> event) {  
    System.out.println("Handshake sent");
 } 
  @Override
  public void receive(PacketReceiveEvent<Handshake> event) { 
    System.out.println("Handshake receive");
  }
}
```
Listening of Handhsake packet does not work neither UPSTREAM nor DOWNSTREAM

**Comment by Exceptionflug** [comment]
Yea thats correct since the channel handlers of protocolize will be injected into the pipeline during the connect. I can try to replace the channel initializer used for the streams.

**Comment by VladMartyshev** [comment]
It would be great

**Comment by Exceptionflug** [comment]
Here you have an experimental build of protocolize 1.4.7 https://file.exceptionflug.de/1567060166_protocolize-plugin.jar

**Comment by VladMartyshev** [comment]
ProtocolLib has ASM library in dependencies. I guess this is for code injections.

**Comment by Exceptionflug** [comment]
Yea maybe. I will take a look into it for a future update.
