### ISSUE TITLE
Sound enum doesn't play the correct sounds 1.19.3

### ISSUE THREAD

**Issue by TauCubed** [Exceptionflug/protocolize#171]
**Describe the bug**
The Sound enum doesn't play the correct sounds when used with `ProtocolizePlayer#playSound(Sound, SoundCategory, float, float)`

**To Reproduce**
1. Create a way to invoke the above method with the sound `Sound.MUSIC_CREATIVE`
2. Join the 1.19.3 server with a 1.19.3 client
3. Invoke the method
4. Observe that a different sound is played.

**Expected behavior**
The correct sound to play.

**Screenshots**
Click the image below to watch the video:
[![Video](https://img.youtube.com/vi/0peasjxZyp4/0.jpg)](https://youtu.be/0peasjxZyp4)

**Proxy environment**
git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510

**Minecraft versions used**
1.19.3 both on client and server.

**Comment by Exceptionflug** [comment]
Hey,

can you check if the issue has been resolved with the latest build?
https://ci.exceptionflug.de/job/Protocolize2/

**Comment by TauCubed** [comment]
![image](https://user-images.githubusercontent.com/35522873/209245634-a971cb91-2070-4258-80bc-b592ef50dab1.png)

**Comment by LaserSlime** [comment]
> ![image](https://user-images.githubusercontent.com/35522873/209245634-a971cb91-2070-4258-80bc-b592ef50dab1.png)

I keep getting this when playing any sound to any player that is using 1.19.3. Any news on when this will be fixed?

**Comment by Dev4lexG** [comment]
@TauCubed can you add one option for ignore/reproduce other sound if the player is 1.19.3 client?

**Comment by Exceptionflug** [comment]
Should be fixed
