### ISSUE TITLE
Velocity 3.2.0-snapshot Issue

### ISSUE THREAD

**Issue by smuddgge** [Exceptionflug/protocolize#177]
**Describe the bug**
Inventories don't seem to work on `3.2.0-snapshot`.
They do however work on `3.1.2`

**To Reproduce**
Have a plugin use this kind of code :
```java
ProtocolizePlayer player = Protocolize.playerProvider().player(this.user.getUniqueId());
player.openInventory(this.inventory);
```

**Expected behaviour**
Inventory opens.

**Behavior**
Error occurs https://pastebin.com/tu6uSs73

**Proxy environment**
`Velocity 3.2.0-snapshot`

**Minecraft versions used**
`1.19.2`

**Comment by Matt-MX** [comment]
Seeing the same problem

**Comment by Exceptionflug** [comment]
Should be fixed with latest build

**Comment by smuddgge** [comment]
Seems to be fixed now, thank you! :3
