### ISSUE TITLE
Protocolize is unable to read packet

### ISSUE THREAD

**Issue by ItsLaivy** [Exceptionflug/protocolize#181]
**Describe the bug**

**To Reproduce**
1, I just place the plugin, and [BungeeLayer](https://www.spigotmc.org/resources/%E2%9C%82%EF%B8%8F-bungee-pack-layer-optimize-resource-pack-sending.94978/) and the bug happens when i send the Oraxen texture.
2. Got an error: [Pastebin](https://pastebin.com/qMLjtmL9)

**Expected behavior**
The texture sending to the player

**Screenshots**
No screenshots

**Proxy environment**
waterfall-1.19-511:
Protocolize version 2.2.5:591;
BungeeLayer version 1.1.0.
(Using ViaVersion on bungee servers)

**Minecraft versions used**
Client: 1.16.5, server: 1.19.2. Tried with 1.19.2

**Note**
i tested with the client version same as the server version, the issue doesn't happens.

**Comment by Exceptionflug** [comment]
Hey, it seems like this is an error of BungeeLayer. Please contact the developer of this plugin regarding this issue.
