### ISSUE TITLE
Protocolize blocked some item manipulations in 1.16.5

### ISSUE THREAD

**Issue by Sanluli36li** [Exceptionflug/protocolize#182]
**Describe the bug**
When I connect to a 1.16.5 Fabric through a Velocity with only Protocolize installed, some client mods (eg: itemscorller, EasierVillagerTrading) for shortcut item operations are completely unavailable
Items will bounce back to their original position after the client appears to manipulate it

Proxy, server, and client do not report any errors

**To Reproduce**
1. install protocolize in velocity, item scroller in client
2. Connect to a 1.16.5 Vanilla or Fabric server via velocity.
3. Use the mass craft function of item scroller in the server
You can see my test here: https://www.youtube.com/watch?v=myojOwnYz-E
In the test, Velocity only installed Protocolize and did not install any other plugins

**Expected behavior**
The client item manipulation mod should work fine

**Screenshots**
See: https://www.youtube.com/watch?v=myojOwnYz-E

**Proxy environment**
velocity-3.2.0-SNAPSHOT-223.jar

**Minecraft versions used**
| client | server | proxy&plugin | protocolize | behavior |
|-|-|-|-|-|
|1.16.5|1.16.5|Velocity-3.2.0|-|work fine|
|1.16.5|1.16.5|Velocity-3.2.0 with ViaVersion 4.5.1|-|work fine|
|1.16.5|1.17.1|Velocity-3.2.0 with ViaVersion 4.5.1|-|work fine|
|1.18.2|1.16.5|Velocity-3.2.0 with ViaVersion 4.5.1|-|work fine|
|1.18.2|1.17.1|Velocity-3.2.0 with ViaVersion 4.5.1|-|work fine|
|1.16.5|1.16.5|Velocity-3.2.0|2.2.5:591|block|
|1.16.5|1.16.5|Velocity-3.2.0 with ViaVersion 4.5.1|2.2.5:591|block|
|1.16.5|1.17.1|Velocity-3.2.0 with ViaVersion 4.5.1|2.2.5:591|work fine|
|1.18.2|1.16.5|Velocity-3.2.0 with ViaVersion 4.5.1|2.2.5:591|block|
|1.18.2|1.17.1|Velocity-3.2.0 with ViaVersion 4.5.1|2.2.5:591|work fine|

**Comment by Exceptionflug** [comment]
Hey, thank you for your detailed issue. Sadly protocolize was never developed with mod support in mind so that it even sometimes works amazes me. There is not anything I can do for you at the moment.
