### ISSUE TITLE
Sending sound to a player kicks them

### ISSUE THREAD

**Issue by james090500** [Exceptionflug/protocolize#183]
**Describe the bug**
Playing sound to a player kicks them with a message

**To Reproduce**
1. Make a plugin to send a sound eg;
```protocolizePlayer.playSound(Sound.valueOf("ENTITY_ARROW_HIT_PLAYER"), SoundCategory.MASTER, 1f, 1f);```
2. Player is kicked

**Expected behavior**
Sound plays and player isn't kicked

**Screenshots**
![image](https://user-images.githubusercontent.com/20372645/222983614-88370106-27ac-438a-b4ba-47dbcd9a2a75.png)

**Proxy environment**
 Velocity 3.2.0-SNAPSHOT (git-e08ffa10-b232)

**Minecraft versions used**
1.19.3 server and client.

**Comment by Nuubles** [comment]
This also happens on Paper 1.19.3 patch version 406 ( paper-1.19.3-406 ), with calls referencing Sound enum value directly instead of valueOf

**Comment by Exceptionflug** [comment]
Thank you for reporting. Should be fixed in the latest build.
