### ISSUE TITLE
Waterfall Support

### ISSUE THREAD

**Issue by Tofuus** [Exceptionflug/protocolize#19]
I'm not sure if you want to support [Waterfall](https://github.com/PaperMC/Waterfall/) but a recent commit breaks the way you register packets.

https://github.com/PaperMC/Waterfall/commit/fa0711d2b8d5e0ef111d7b391831a154abe9223c

Changes an array of constructors to an array of suppliers.

**Comment by Exceptionflug** [comment]
Hey, thank you for your submission. Here is the latest protocolize release supporting Waterfall: https://github.com/Exceptionflug/protocolize/releases/tag/v1.4.7

**Comment by Tofuus** [comment]
Thanks for the quick fix as usual!
