### ISSUE TITLE
Can not open cartography table

### ISSUE THREAD

**Issue by Damianquq** [Exceptionflug/protocolize#190]
**Describe the bug**
cartography table doesnt open

**To Reproduce**
1. try to open cartography table

**Expected behavior**
Open cartography table

**Screenshots**
![image](https://user-images.githubusercontent.com/64448119/235914473-b8a84457-5475-4721-8460-ec2f28bf80be.png)

**Proxy environment**
Velocity 3.2.0

**Minecraft versions used**
Paper 1.19.4 - 521

**Comment by Athar42** [comment]
@Exceptionflug Sorry again, bumped it overthere as I'm unsure you get notified on closed requests :)

**Comment by Yertled** [comment]
We also have this issue on our server. I would love for it to get fixed.

**Comment by Athar42** [comment]
Yeah, that's it, or you recompile with the fix... (which is quite a mess with all the dependencies).

We made it working on our server at least, but that required a few tweak to get all of those dep. in line (not me, I don't know enough on Java/graddle/ and other kind of thing that's involved there).

Also, I think it wasn't directly in Protocolize, but in https://github.com/Exceptionflug/protocolize-data

See the fix by Yive last month in this issue request : https://github.com/Yive/protocolize-data/commit/99c9f08fc37e692cc1d651b4db28fe6cfccbf5f5
That's almost the same as the fix done for the Stone cutter
https://github.com/Exceptionflug/protocolize-data/commit/7fc0c3b7a2a02d9fda2ad5545a6cc391813761ce


Not a lot work to do, but the maintener might not have the time to apply this simple fix :)

**Comment by Exceptionflug** [comment]
> Not a lot work to do, but the maintener might not have the time to apply this simple fix :)

Exactly :)

Sorry for the late response but yeah, this project is not getting so much time from me anymore. Is it possible for you to create a pull request for that fix?

**Comment by Athar42** [comment]
You see the author merge request, so we are good now, just need a new build of Protocolize using this change, and that'll be perfect :P 

Thanks for your work on this ;)

**Comment by Exceptionflug** [comment]
Builds are happening nightly, but I scheduled one for now.
