### ISSUE TITLE
Protocolize is causing viaversion bugs

### ISSUE THREAD

**Issue by xF3d33** [Exceptionflug/protocolize#191]
**Describe the bug**
protocolize on the proxy is causing viaversion errors in backend servers.

somehow protocolize is causing viaversion to panic in terms of entities or another subject that causes connectivity failures.

**To Reproduce**
1. create a backend server 1.19.4 behind waterfall proxy with protocolize installed, then add viaversion for 1.19.4 and let players join, you'll se the error for some players

**Expected behavior**
no errors

**Screenshots**
https://mclo.gs/kHkh0HO
https://mclo.gs/vpldSpT

**Proxy environment**
waterfall 526

**Minecraft versions used**
1.19.4

**Comment by Exceptionflug** [comment]
Hey, this should not be a protocolize issue at all. Please check other proxy plugins and/or spigot plugins for packet interactions with the GameProfile of the players.

The reason why this is not a protocolize issue is simple: Protocolize doesn't touch the Player Info packets at all.
