### ISSUE TITLE
Is there a way to get access to additional legacy module API?

### ISSUE THREAD

**Issue by astro-angelfish** [Exceptionflug/protocolize#193]
I was making velocity plugin on head of servers running on 1.12.2, which requires [Additional Legacy Module](https://ci.exceptionflug.de/job/Protocolize-Legacy-Data/).

I tried to add it as a dependency to my plugin using gradle, but I didn't found it in your maven repository.
So I wonder how I can use the legacy packet or is there a replacement?

**Comment by Exceptionflug** [comment]
Hey, it is not necessary to have the legacy support module on classpath during compile time. It is only required to run during runtime. So no gradle/maven dependency needed. Just use the normal protocolize api.

**Comment by astro-angelfish** [comment]
I see. Thanks for answering.
