### ISSUE TITLE
Can't send PlayerPosition packet

### ISSUE THREAD

**Issue by iminlikewithyou** [Exceptionflug/protocolize#209]
**Describe the bug**
I can't send a PlayerPosition packet to a client on (seemingly) any Minecraft version. Maybe I'm stupid and these packets aren't sendable but I'm quite unsure

java.lang.IllegalStateException: Cannot send dev.simplix.protocolize.data.packets.PlayerPosition to players with protocol version X

**To Reproduce**
![CleanShot 2023-12-05 at 10 25 23@2x](https://github.com/Exceptionflug/protocolize/assets/20297536/b31921b8-5dbe-4e5a-aa00-74b1c3110ee1)

**Proxy environment**
Velocity 3.2.0-SNAPSHOT, no other plugins, using the latest Protocolize 2.3.1

**Minecraft versions used**
Minecraft 1.20.2 (protocol version 764)
Minecraft 1.17.1 (protocol version 756)
Minecraft 1.8 - 1.8.9 (protocol version 47)

**Comment by Exceptionflug** [comment]
Hey, in this case the packet is implemented by Velocity (com.velocitypowered.proxy.protocol.packet.Respawn) and you can use this directly in a PacketListener for example. All you have to do is to add the velocity-proxy module to your classpath during compile time. For example by locating a jar file on your drive with system scope.

**Comment by Exceptionflug** [comment]
Closed since no reaction anymore.
