### ISSUE TITLE
pipeling errors

### ISSUE THREAD

**Issue by AceSardonyx** [Exceptionflug/protocolize#210]
This is a pipeline issue that told me to report it so here it is

1. On velocity server on backend with others running
2. stop/restart the server
3. pipeline error

I have 4 random servers in my "try" servers block in velocity.toml
I expect for fall back to happen or graceful disconnnect

Running Velocity 3 (latest as of this date)
Viaversion only installed on backends due to cascading errors when using protocolize with vv on proxy
The restarted backend is a 1.12.2 hub server and the other 3 are 1.19.4 & 1.20 servers which should have gotten redireced to

Short log:
<script src="https://gist.github.com/AceSardonyx/554adc0b1c8ff44f2cd86d08b735796c.js"></script>

**Comment by Exceptionflug** [comment]
Hey, thank you for reaching out. The log you provided only shows error caused by the plugin `me.bhop.velocityloadbalancer.LoadBalancerPlugin`. Protocolize is to this point not involved. Is this the only error you like to submit?

**Comment by AceSardonyx** [comment]
Yes I will send the full log including startup. Maybe you could help me point out what the issue is?
I have recently switched from waterfall to velocity in favor of how much paper favors it and innovation etc.
I'm finding many drawbacks in compatibility and features that I originally have had with waterfall.
One I am facing right now is servers, redirection, and load balancing.
I am trying to find ways to do it like I had set up on waterfall.
I am new to velocity and am still learning, so could you help me figure this one out please? And thanks 😸

**Comment by AceSardonyx** [comment]
Though redirect DOES work now, I still get these errors: https://mclo.gs/MjMfgeA (this is the whole log)
Wondering how to remove the verbose channel msging logs with viabackwards too.
And whenever people join, they do not log into the same server they log off on. I am not sure if this is due to the "load balancing" because I have tried doing it with no players on and vice versa with the same result. Not that it matters. My question in my comment above is more important. But thank you very much for any help :)

**Comment by Exceptionflug** [comment]
Hey, this is still not a protocolize issue. Please contact ViaBackwards support for this.
