### ISSUE TITLE
update to 1.20.3/1.20.4 please :)

### ISSUE THREAD

**Issue by homerek111** [Exceptionflug/protocolize#212]
1.20.3 / 1.20.4 are not supported yet, please update :)

**Comment by Exceptionflug** [comment]
?
![firefox_B8an9LECJT](https://github.com/Exceptionflug/protocolize/assets/13393754/28378312-d7bd-42b3-8c8f-b4f10cafba79)

**Comment by LaserSlime** [comment]
They might be talking about #211

**Comment by homerek111** [comment]
> They might be talking about #211

exactly - inventory does not work properly on 1.20.3 / 1.20.4 versions

**Comment by Exceptionflug** [comment]
Okay I will close this then.
