### ISSUE TITLE
When installing this protocolize plug-in, failure to enter the server using ViaVersion

### ISSUE THREAD

**Issue by wldtb** [Exceptionflug/protocolize#215]
![QQ截图20240102091937](https://github.com/Exceptionflug/protocolize/assets/136847582/aa7ac207-f298-4958-a2d1-a4a52a836b1e)

**Comment by Exceptionflug** [comment]
Not enough information provided. Please stick to the issue template.

**Comment by KotlinFactory** [comment]
Ha gay

Nico Britze ***@***.***> schrieb am Di., 2. Jan. 2024, 18:53:

**Comment by wldtb** [comment]
In short, protocolize and ViaVersion do not use together. Install protocolize and see an issue in images with ViaVersion. You can test this for yourself, thanks!

**Comment by LaserSlime** [comment]
You've probably installed ViaVersion on your proxy. You shouldnt do that, it causes a lot of issues in general.

**Comment by Exceptionflug** [comment]
Yes as @LaserSlime already mentioned, don't use viaversion on the proxy
