### ISSUE TITLE
[Question] Missing Enderchast sounds?

### ISSUE THREAD

**Issue by hitech95** [Exceptionflug/protocolize#216]
**Describe the bug**
Are enderchest sounds missing?
I've not been able to reproduce them.

After looking in the Sound enum I cant find them.

**Proxy environment**
Velocity

**Minecraft versions used**
1.20.1

**Comment by Exceptionflug** [comment]
Hey,
![mQXwFsrBB9](https://github.com/Exceptionflug/protocolize/assets/13393754/8df25172-4c19-4fbd-ac37-fbb8e80dba2d)
what about this?

**Comment by hitech95** [comment]
On 1.20.1 version those are not available.
Newer versions sthrows errors due to the rename of the GRASS_BLOCK thing.
