### ISSUE TITLE
Errors with the latest devbuild (#928)

### ISSUE THREAD

**Issue by NoltoxGit** [Exceptionflug/protocolize#217]
**Describe the bug**
When I start my server with the latest version of Protocolize with Velocity, my console spams with a startup error.

**To Reproduce**
1. Get the latest devbuild here (https://ci.exceptionflug.de/job/Protocolize2/928/)
2. Get the latest velocity version
3. Start the server
4. See errors

**Expected behavior**
No errors in my console.

**Logs**
https://mclo.gs/CPgiLNj#L1

**Proxy environment**
I use the version of velocity : `velocity-3.3.0-SNAPSHOT-312`
I use thses plugins :
![image](https://github.com/Exceptionflug/protocolize/assets/75265787/216756a4-516b-43c5-aaaa-fb4031c540ac)

**Comment by Exceptionflug** [comment]
Hey, this issue has already been fixed in build 929 released today. Please download the latest version. Thank you.

**Comment by NoltoxGit** [comment]
Yes, thank you so much !
