### ISSUE TITLE
How get ItemType?

### ISSUE THREAD

**Issue by 1RIeN1** [Exceptionflug/protocolize#22]
I want to get the item with config.yml, but how to get it?

**Comment by Exceptionflug** [comment]
Please explain what do you want to do. Protocolize has nothing to do with configuration files. If you want to store items in a configuration file, please take a look at https://github.com/Exceptionflug/mccommons

**Comment by 1RIeN1** [comment]
I want to get an item like wood, then in bukkit you can Material.getMaterial ();If here, something like that?

**Comment by Exceptionflug** [comment]
ItemType.valueOf(String) maybe?

**Comment by 1RIeN1** [comment]
Thanks
