### ISSUE TITLE
Client times out on latest version of Velocity.

### ISSUE THREAD

**Issue by slash1div** [Exceptionflug/protocolize#222]
**Describe the bug**
When Protocolize is installed on the latest version of Velocity, the client times out.

**To Reproduce**
1. Install Protocolize on Velocity
2. Connect to the server on client
3. See error

**Expected behavior**
You are expected to be able to join the server, which you are able to without Protocolize.

**Screenshots**
Console error and client message.
![brave_JG1nRnJir6](https://github.com/Exceptionflug/protocolize/assets/83387831/44b48d32-52f0-40cc-b67a-9f96205b13e0)
![image](https://github.com/Exceptionflug/protocolize/assets/83387831/1ab6b674-79fc-4fb8-b5b1-01baea56c431)

**Proxy environment**
Velocity 3.3.0-SNAPSHOT Build #331 - Latest at this moment.
Plugins: `Protocolize, EnhancedVelocity, Litebans, LuckPerms, MiniMOTD, TitleAnnouncer, Velocitab`

**Minecraft versions used**
Velocity 3.3.0-SNAPSHOT Build #331 on proxy. - Latest at this moment.
1.20.2 Purpur servers on latest build.
Minecraft 1.20.2 on client.

**Comment by mellowism** [comment]
I have the same issue running 1.20.4

**Comment by x1p** [comment]
Same for me. Happens on Velocity from build 329 and newer.

**Comment by NoltoxGit** [comment]
I also have an error with the latest build, and when I go back to Velocity version 327, I don't get any more errors.
Logs : https://mclo.gs/soNtBro

**Comment by Exceptionflug** [comment]
Hey, as promised this is now fixed with the latest build. Download it here: https://exceptionflug.de/protocolize
