### ISSUE TITLE
Kick on inventory open

### ISSUE THREAD

**Issue by overkidding** [Exceptionflug/protocolize#224]
**Describe the bug**
Players get kicked for "DecoderException : io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1 @ io.netty.handler.codec.MessageToMessageDecoder:98"

**To Reproduce**
Just put latest released protocolize, flamecord and viaversion/viarewind join and try to open an inventory like a server selector

**Expected behavior**
Should open inventory and not kick players

**Screenshots**
https://imgur.com/a/YZ5IYPj

**Proxy environment**
FlameCord Latest

**Minecraft versions used**
Lunar Client, BungeeCord 1.7-1.20.4, Spigot 1.8.8 with viaversion and viarewind

**Comment by Exceptionflug** [comment]
Hey,
Neither Flamecord or ViaVersion on Proxy is officially supported by us. Please use a supported proxy software / fork and don't run ViaVersion on the proxy.

**Comment by overkidding** [comment]
> Hey, Neither Flamecord or ViaVersion on Proxy is officially supported by us. Please use a supported proxy software / fork and don't run ViaVersion on the proxy.

I do not run ViaVersion on proxy only on spigot servers

**Comment by overkidding** [comment]
About FlameCord, they told us to contact protocolize, you're telling us to contact them what should i do? 🤣

**Comment by Exceptionflug** [comment]
> > Hey, Neither Flamecord or ViaVersion on Proxy is officially supported by us. Please use a supported proxy software / fork and don't run ViaVersion on the proxy.
> 
> I do not run ViaVersion on proxy only on spigot servers

Sorry then I read that wrong.



> About FlameCord, they told us to contact protocolize, you're telling us to contact them what should i do? 🤣

No, I said that we don't support FlameCord at all. An excellent example on why did you provide with this issue. Try to recreate this exception with a supported BungeeCord fork like Waterfall. If it also occurs on Waterfall or vanilla BungeeCord, then I have to take a look at it.

**Comment by overkidding** [comment]
> > > Hey, Neither Flamecord or ViaVersion on Proxy is officially supported by us. Please use a supported proxy software / fork and don't run ViaVersion on the proxy.
> > 
> > 
> > I do not run ViaVersion on proxy only on spigot servers
> 
> Sorry then I read that wrong.
> 
> > About FlameCord, they told us to contact protocolize, you're telling us to contact them what should i do? 🤣
> 
> No, I said that we don't support FlameCord at all. An excellent example on why did you provide with this issue. Try to recreate this exception with a supported BungeeCord fork like Waterfall. If it also occurs on Waterfall or vanilla BungeeCord, then I have to take a look at it. We dropped FlameCord support a few years ago because they do changes to the protocol / netty implementation pretty often. Additionally, FlameCord is payed resource which I don't have access to. I can't take a look at their source code to see what make some problems and I can't even run it since I have no license for it.

The fact is, i need a 1.7 to 1.20.4 bungeecord so FlameCord is the only one supported atm

**Comment by Exceptionflug** [comment]
Maybe there will be some FlameCord support if the FlameCord team decides to contribute it to protocolize.

**Comment by Exceptionflug** [comment]
Will be tracked here: https://github.com/Exceptionflug/protocolize/issues/226
