### ISSUE TITLE
endless pinging of the server

### ISSUE THREAD

**Issue by TofaDev** [Exceptionflug/protocolize#228]
**Describe the bug**
when I try to log in to the server, I can't do this, and if I update the list of servers, I get endless pinging
at the same time, I get this log in the console, attached the picture below

**Screenshots**
![изображение](https://github.com/Exceptionflug/protocolize/assets/94196761/5afae2d4-c5cc-4b6f-bb4a-8600a14fe980)

**Proxy environment**
I am using Velocity Velocity 3.3.0-SNAPSHOT (git-b9b11665-b343) and protocolize version 2.3.3:926

**Minecraft versions used**
Minecraft 1.20.4

**Comment by Exceptionflug** [comment]
Hey, you are using an outdated build of Protocolize. Please download the latest version here: https://exceptionflug.de/protocolize
