### ISSUE TITLE
Inventories don't open for 1.20.5+ clients

### ISSUE THREAD

**Issue by LaserSlime** [Exceptionflug/protocolize#241]
**Describe the bug**
Opening inventories for people on 1.20.5 and above doesn't work, most likely due the new item components.

**To Reproduce**
1. Try to open inventory using protocolize
2. See that it doesn't work and causes errors.

**Expected behavior**
Inventories should open.

**Proxy environment**
git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a65bb68:578

**Minecraft versions used**
Server version: 1.20.4
Client version: 1.20.6

**Comment by Exceptionflug** [comment]
Item components are now support as part of Protocolize v2.4.0
