### ISSUE TITLE
Pipeline is not initialized

### ISSUE THREAD

**Issue by dqnza** [Exceptionflug/protocolize#242]
**Describe the bug**
[11:17:20 ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: Pipeline is not initialized. This is a bug. Please report. Pipeline handlers = {}
[11:17:20 ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: Initializer: dev.simplix.protocolize.velocity.netty.ProtocolizeBackendChannelInitializer

I don't know what is this error about, because this error never shown before on my proxy. and i don't have Geyser or Floodgate installed on my Proxy Server.
The error message will appear once after I start or restart the proxy.
![Protocolize img 2](https://github.com/Exceptionflug/protocolize/assets/129637963/fe4ab255-4d1e-4485-b1f6-31fc0d573900)

**To Reproduce**

**Expected behavior**
The error shouldn’t appear

**Screenshots**
![Protocolize Error](https://github.com/Exceptionflug/protocolize/assets/129637963/da1d8f79-b2a6-4146-af66-ff47980fe62b)

**Proxy environment**
Velocity
List of the plugin that installed on my Proxy:
![Velocity Plugin](https://github.com/Exceptionflug/protocolize/assets/129637963/d27e95dd-e71f-45c0-bb11-e5e959fe649e)

**Minecraft versions used**
Only proxy server.

**Comment by Exceptionflug** [comment]
I assume VPacketEvents is also incompatible with Protocolize. Can you verify this?
