### ISSUE TITLE
Unable to Read Item Stack from Buffer in Protocol Version 767

### ISSUE THREAD

**Issue by var1nthon** [Exceptionflug/protocolize#253]
**Describe the bug**
When using Protocolize with protocol version 767, an error occurs while attempting to read item stacks from a buffer. The error message indicates that Protocolize cannot find the component type for protocol version 767, leading to an 'IllegalStateException'.

**To Reproduce**
1. Use Protocolize with a server or client running protocol version 767.
2. Perform an action that involves reading or writing item stacks, such as clicking a window slot or interacting with items in an inventory.
3. Observe the error in the console.

**Expected behavior**
Protocolize should successfully read and write item stacks without errors for all supported protocol versions, including version 767.

**Screenshots**
![image](https://github.com/user-attachments/assets/93c3bf59-7dab-4714-a8fc-de6bd716a28b)

**Proxy environment**
Proxy Server: Velocity Proxy
Version: 3.3.0-SNAPSHOT-413

**Minecraft versions used**
Client Version: 1.21 (Protocol Version 767)
Server Version: 1.21

**Additional Information**
Protocolize debug: 
[protocolize-debug.txt](https://github.com/user-attachments/files/16448643/protocolize-debug.txt)
Velocity log: 
[latest.log](https://github.com/user-attachments/files/16448647/latest.log)
Paper log: 
[latest.log](https://github.com/user-attachments/files/16448648/latest.log)

**Comment by Exceptionflug** [comment]
Hey, it seems like you are running an outdated version of protocolize. Please update to the latest release here: https://exceptionflug.de/protocolize

**Comment by Exceptionflug** [comment]
It seems like a duplicate of https://github.com/Exceptionflug/protocolize/issues/249

**Comment by var1nthon** [comment]
Ok, Thank u
