### ISSUE TITLE
support velocity proxy

### ISSUE THREAD

**Issue by robinbraemer** [Exceptionflug/protocolize#26]
As usage for the awesome [Velocity](https://github.com/VelocityPowered/Velocity) proxy increases and many bigger networks start using it, it would be great and beneficial for protocolize to add support for the velocity proxy.

**Comment by Exceptionflug** [comment]
There will be no support for velocity proxy since it differs too much from bungeecord. Any developer can fork Protocolize and add support for velocity on their own.
