### ISSUE TITLE
Cannot retrieve 1.5.1 or 1.5.2 on Maven

### ISSUE THREAD

**Issue by paul-maxime** [Exceptionflug/protocolize#27]
I get the following error when trying to download 1.5.1-SNAPSHOT or 1.5.2-SNAPSHOT through Maven:

> Failure to find de.exceptionflug:protocolize:pom:${revision} in http://mvn.exceptionflug.de/repository/exceptionflug-public/ was cached in the local repository, resolution will not be reattempted until the update interval of exceptionflug has elapsed or updates are forced

The problem probably comes from the `${revision}` tag not getting replaced.

Previous versions, including 1.5.0-SNAPSHOT, work fine.

**Comment by Exceptionflug** [comment]
Hello,

As you can see here:
![Repo](https://img.exceptionflug.de/1579344310_firefox_HEmRPtK1nY.png)
The versions are correctly in the repo. I'm using those versions myself on another computer and it works fine. Please try to download all artifacts using the -U parameter in the maven command line.

**Comment by paul-maxime** [comment]
Hi, I am using IntellJ IDEA.

I checked a bit more and I think the problem comes from the `.pom` file of `protocolize-api`:

1.5.0:
http://mvn.exceptionflug.de/repository/exceptionflug-public/de/exceptionflug/protocolize-api/1.5.0-SNAPSHOT/protocolize-api-1.5.0-20191210.170924-2.pom
```
<parent>
<groupId>de.exceptionflug</groupId>
<artifactId>protocolize</artifactId>
<version>1.5.0-SNAPSHOT</version>
</parent>
```

1.5.2:
http://mvn.exceptionflug.de/repository/exceptionflug-public/de/exceptionflug/protocolize-api/1.5.2-SNAPSHOT/protocolize-api-1.5.2-20200118.234950-41.pom

```
<parent>
<groupId>de.exceptionflug</groupId>
<artifactId>protocolize</artifactId>
<version>${revision}</version>
</parent>
```

**Comment by Exceptionflug** [comment]
I redeployed version 1.5.2-SNAPSHOT. Please try again using -U

**Comment by paul-maxime** [comment]
Thanks, `1.5.2-SNAPSHOT` works fine now!
