### ISSUE TITLE
NullPointerException on PacketRegisteration

### ISSUE THREAD

**Issue by ThatKawaiiAllen** [Exceptionflug/protocolize#3]
https://pastebin.com/sz6RpiNa

https://github.com/HexagonMC/BungeeCord -> The BungeeCord I'm using

**Comment by Exceptionflug** [comment]
It seems like you are using an unsupported version of bungeecord. You can try this release of Protocolize: https://github.com/Exceptionflug/protocolize/releases/tag/v1.2.0_Hotfix

**Comment by ThatKawaiiAllen** [comment]
Is there any way to make it compatible with latest protocolize?

**Comment by Exceptionflug** [comment]
Please take a look at this commit from the official bungeecord repo: https://github.com/SpigotMC/BungeeCord/commit/9133a6f511b4cfaca5e6a6671b58a6c3b10821ab

These changes have to be done in your bungeecord version in order to allow protocolize 1.3 and newer to register packets.

**Comment by Exceptionflug** [comment]
Unsupported BungeeCord fork. Won't support.
