### ISSUE TITLE
Graphical Bug

### ISSUE THREAD

**Issue by zadrarion** [Exceptionflug/protocolize#35]
Hi guys,

I use protocolize for create fake inventory with bungee.
All works fine (thanks for this awesome lib) but when I open the inventory example, if I click on item in my inventory, he disappeared.

If i try to interract with this new empty slot, the item come back but i would prefer if i can avoid this "bug"

![image](https://user-images.githubusercontent.com/13852927/80321441-47e76e80-881d-11ea-8a9b-eda68ebe488c.png)

I only have my plugin with protocolize on the proxy.
If you need more details, let me know.

(PS: I'm french, and I think i'm really bad for write and speak in english, i'm sorry if this post is awfull)

**Comment by Exceptionflug** [comment]
Hey,

thank you for your interest. Did you already try to cancel the InventoryClickEvent?

**Comment by zadrarion** [comment]
Hello,

Yes, i've cancel the InventoryClickEvent, so when i click on the Item in the fake GUI, nothing happen but when i click on item in my personal Inventory. my item dissapeared.

It's only graphical but it's annoying :/

Thanks for your help :D

**Comment by Exceptionflug** [comment]
Hey,

yeah I know what you mean. I will look forward to fix this in the next releasen. Since this is not a critical bug.

**Comment by zadrarion** [comment]
After some try, it would appear that the kae inventories trigger the opening and click event for each click. I don't know if this could help you. If i find any others informations, i will tell you.

**Comment by Exceptionflug** [comment]
This will not be implemented.

**Comment by galexrt** [comment]
I was able to "workaround" this bug by having Bungeecord send a "message" (I'm using Proton, though Plugin message should work as well) whenever the player presses a slot that is not "managed" by, e.g, the inventory opened. The "message" for simplicity just contains the UUID of the player.

Proxy side code (inventory creation code):
```java
Inventory inventory = new Inventory(InventoryType.GENERIC_9X4);
# For `InventoryType.GENERIC_9X4` the `maxSlot` is 35
int maxSlot = 35;
# ...
inventory.onClick(click -> {
    if (click.slot() > maxSlot) {
      # Send message to server
      return;
    }
    # ...
};
```

The code on the server side will then when a messages is received from the proxy run:
```java
Player player = getServer().getPlayer(message.getUuid());
player.updateInventory();
```

It isn't perfect but making it much better than when the items simply disappear.
It is probably a good idea to add a "debounce" / cooldown / queue logic on the server side to only update the inventory every few ticks / seconds and not on every click.

Would be cool if that graphical bug could be fixed somehow without creating a "system" like that.
