### ISSUE TITLE
Missing Skull Creations to ItemStack

### ISSUE THREAD

**Issue by 0xLyptox** [Exceptionflug/protocolize#5]
Please update your **Items-Module** within the **ItemStack** Class to create **custom Skulls**.
Missing Methods:

-  *void setOwner(String owner)
-  *String getOwner()
-  boolean isSkull()

Thanks

**Comment by Exceptionflug** [comment]
Hey thanks for your intereset,

one question. What do you want to get returned by isSkull? True if the ItemType is PLAYER_HEAD or true if the ItemType is any skull type like SKELETON_SKULL?

**Comment by 0xLyptox** [comment]
Hey,

If the ItemType is an PLAYER_HEAD i mean.

**Comment by Exceptionflug** [comment]
Please take a look at https://github.com/Exceptionflug/protocolize/commit/18448a7da84d05cf0c49cc4f645d1f3bd1e59d55
These changes will be part of the next scheduled release v1.4.4 after Minecraft 1.14.3 releases. If you want to use those methods now, you have to manually build your own version of Protocolize using Maven.

**Comment by 0xLyptox** [comment]
Thank you
