### ISSUE TITLE
Unknown Rrror

### ISSUE THREAD

**Issue by ApoCalispsiS** [Exceptionflug/protocolize#51]
I am really completely unaware of this error, I am not a developer, but I wish you could help me with this problem. I don't know the cause or why, I just posted this issue in the discussion of this plugin and they sent me here.

Here is the error report: https://pastebin.ubuntu.com/p/S4CM5wPY79/

I'm very sorry if I haven't followed the directions in this post.

**Comment by Exceptionflug** [comment]
Hey,

this is very strange, Could you tell me please what you was doing atm when this error has occurred?

**Comment by MeowMiaoMiao** [comment]
> Hey,
> 
> this is very strange, Could you tell me please what you was doing atm when this error has occurred?

It seems that this problem occurs when the KICK packet is modified

**Comment by Exceptionflug** [comment]
This makes no sense since the packet that produces this error is fired when switching gamemodes.

**Comment by Exceptionflug** [comment]
Since this issue is inactive, I will close it. Please reopen necessary.
