### ISSUE TITLE
Bug with typical inventory size for protocol version 751

### ISSUE THREAD

**Issue by LogGits** [Exceptionflug/protocolize#52]
**Describe the bug**
Cannot find Generic9x3 typical inventory size for protocol version 751 (1.16.2 which just came out)

**To Reproduce**
Create an inventory with the size of generic9x3 then use a for loop to fill the inventory with a specific item.
Example:
```java
public static Inventory createInventory (int rows, String name, ItemStack fill) {
    final Inventory inv = new Inventory(InventoryType.getChestInventoryWithRows(rows), new TextComponent(name));
    for (int i = 0; i < inv.getType().getTypicalSize(ProxyServer.getInstance().getProtocolVersion()); i++) {
        if (inv.getItem(i) == null) inv.setItem(i, fill);
    }
    return inv;
}
```
**Expected behavior**
return 27;

**Proxy environment**
Waterfall version git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8f9f435:368

**Minecraft versions used**
client uses 1.15.2, the minecraft server is on 1.15.2 and the proxy is on 1.16-R0.4

**Comment by JavaFactoryDev** [comment]
Hi,

Protocolize will be updated for 1.16.2 soon. There were some breaking changes for this version.

Regards,
- Leonhard

**Comment by Exceptionflug** [comment]
Support for 1.16.2 is now added: https://github.com/Exceptionflug/protocolize/releases/tag/v1.6.2

Pls close if problem solved
