### ISSUE TITLE
InventoryClick

### ISSUE THREAD

**Issue by lucianxd16** [Exceptionflug/protocolize#6]
When you cancel the inventory click event, you can steal items shifting or pressing key numbers, is there a way to cancel all of this, I'm using the last version of bungee and protocolize

**Comment by Exceptionflug** [comment]
Hey, on which minecraft client version does this occur?

**Comment by lucianxd16** [comment]
Im trying in 1.8.9 i am trying to cancel players stealing items from protocolize inventories with shift and click

**Comment by Exceptionflug** [comment]
Yep I already reproduced this. I will take a detailed look at this when I'm back home.

**Comment by lucianxd16** [comment]
Ok thanks, i am waiting for your reponse

**Comment by Exceptionflug** [comment]
Fixed as you can see [here](https://file.exceptionflug.de/1560360707_Qyvag9LnEm.mp4). Update will be part of release v1.4.4

**Comment by lucianxd16** [comment]
Ok i will be waiting the update
