### ISSUE TITLE
Don't know what item 835:0 is at version 498

### ISSUE THREAD

**Issue by MeowMiaoMiao** [Exceptionflug/protocolize#61]
![QQ截图20200917142605](https://user-images.githubusercontent.com/29674595/93428281-bbd00380-f8f1-11ea-9448-64451f4a6023.jpg)

**Comment by MeowMiaoMiao** [comment]
latest build version

**Comment by Exceptionflug** [comment]
Hello, thank you for reporting. I will resolve this soon.
