### ISSUE TITLE
Disconnect when items interact

### ISSUE THREAD

**Issue by MeowRay** [Exceptionflug/protocolize#62]
Occurs occasionally Uncertain reproduction conditions
protocolize version: latest
bungeecord: 1.16.3
spigot: 1.8.8
client: 1.16.2

![QQ截图20201012204210](https://user-images.githubusercontent.com/29674595/95747812-916f2d00-0c88-11eb-8a96-3d578b47e8e3.jpg)

**Comment by MeowRay** [comment]
![Uploading QQ截图20201012204945.jpg…]()

**Comment by Exceptionflug** [comment]
Hey, please send the contents of the protocolize.log file.

**Comment by MeowRay** [comment]
> Hey, please send the contents of the protocolize.log file.

[protocolize.log](https://github.com/Exceptionflug/protocolize/files/5393585/protocolize.log)

**Comment by Exceptionflug** [comment]
Your protocolize.log file does not confirm your stated versions from above. You said client version is 1.16.2 but protocolize.log is reporting version 47 (1.8.x) and 107 (1.9). Please download the following build of protocolize and send a new protocolize.log: https://ci.exceptionflug.de/job/Protocolize/lastSuccessfulBuild/artifact/protocolize-plugin/target/protocolize-plugin.jar

**Comment by Exceptionflug** [comment]
Since there is no reaction, I will close this for now.
