### ISSUE TITLE
Protocolize Doesn't know what item 758:0 is at version

### ISSUE THREAD

**Issue by plebexer** [Exceptionflug/protocolize#66]
This is happening again to me, but now with 1.16.4, i installed the lastest protocolize version because i updated viaversion so players can join with 1.16.4 and now im getting spammed by these errors again:
https://pastebin.com/FTsRBk2T

**Comment by Exceptionflug** [comment]
Yea I already fixed this issue. Please download the latest build from our ci server: https://ci.exceptionflug.de/job/Protocolize/lastSuccessfulBuild/artifact/protocolize-plugin/target/protocolize-plugin.jar
