### ISSUE TITLE
[Protocolize] Don't know what item 383:0 is at version 47 

### ISSUE THREAD

**Issue by crafter23456** [Exceptionflug/protocolize#67]
**Describe the bug**
Selfdescribing

**Proxy environment**
Waterfall newest version
![image](https://user-images.githubusercontent.com/64259198/100527965-c6ebbd80-31d7-11eb-823b-63c4b47659dd.png)

**Minecraft versions used**
Paper 1.8.8, Paper 1.16.4.
but version 47 is 1.8.8

**Comment by Exceptionflug** [comment]
After some research: Item 383 with a durability of 0 is not a valid Minecraft spawn egg. So the warning message is correct. You should check the players inventories for invalid items.

Reference: https://www.digminecraft.com/lists/item_id_list_pc_1_8.php
