### ISSUE TITLE
Force shutdown of the client results in an error.

### ISSUE THREAD

**Issue by LemonCaramel** [Exceptionflug/protocolize#68]
**Describe the bug**
Force shutdown of legacy clients results in an error.

https://pastebin.com/rT9cnszx

**To Reproduce**
1. join as a legacy client ( < 1.13)
2. force shutdown client 
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/45729082/103475975-31a2a100-4df5-11eb-838b-30eae5b95ec4.png)

**Proxy environment**
Please let us know which Proxyserver and what version you are running.
Please also let us know which other plugins are running on your proxy server.

Waterfall 1.16.4
No plugins or Viaversion. (Same)

**Minecraft versions used**
If applicable, tell us the used minecraft client AND server versions that are involved in this problem.

1.12.2 ~ 1.16.4 server
1.12.2 client (maybe only legacy clients are experiencing this problem)

**Comment by Exceptionflug** [comment]
Hey,

thank you for reporting. This is a normal BungeeCord exception that get's thrown if a client unexpectedly closes the connection. This is no problem of protocolize and can safely be ignored.

**Comment by LemonCaramel** [comment]
I know that this is not a plugin problem. I just want to deactivate the message.

**Comment by Exceptionflug** [comment]
This is sadly not possible. This exception would also be printed without Protcolize. Please open an issue on the GitHub Repo of BungeeCord.

**Comment by LemonCaramel** [comment]
Thank you for your answer!
