### ISSUE TITLE
EXCEPTION CAUGHT IN DECODER | UPSTREAM

### ISSUE THREAD

**Issue by gameszaum** [Exceptionflug/protocolize#71]
I created and order the custom Inventory to the ProxiedPlayer and just don't open it. I have used the FlameCord (Waterfall/Travertine fork) for server instance and 1.8.8 for minecraft client. For the client, doesn't appear nothing, but in the server console shows a lot of exceptions. I expected to open the inventory for client, following the Protocolize wiki, that's the error.

https://pastebin.com/9kEeXx5w

**Comment by Exceptionflug** [comment]
Hey, please send the full log of the proxy server.

**Comment by gameszaum** [comment]
Ok, here is the full log of the proxy server, thanks for answer.

https://pastebin.com/XKKaJr3n

**Comment by Exceptionflug** [comment]
What java version are you running?

**Comment by gameszaum** [comment]
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

**Comment by Exceptionflug** [comment]
I guess this is may be related to your unsupported BungeeCord fork and / or your Anitbots plugin.

**Comment by gameszaum** [comment]
Lol, but i'm using flamecord, a famous BungeeCord fork. Must be the Antibots plugin which I'm using, what do you suggest?

**Comment by Exceptionflug** [comment]
You could try to test this with:

1. Vanilla Waterfall + Antibots
2. Flamecord + Without Antibots
3. Vanilla Waterfall + Without Antibots

Flamecord may be a famous fork but is not officially supported by Protocolize.

**Comment by gameszaum** [comment]
Okay, sorry for delay, I have tested all options and still the error.

https://pastebin.com/qjtqFcMA - error
https://pastebin.com/zSfxHU6i - code

Ps: I have used the latest Waterfall and Bungeecord version for tests.

**Comment by Exceptionflug** [comment]
Short question: Are you using Protocolize as a plugin installed on your proxyserver or do you accidentally shade protocolize into your own plugin jar? Please check this out.

**Comment by gameszaum** [comment]
Holy man, sorry about that, I was shading protocolize in my project. Now it's working, thank you for your help.
