### ISSUE TITLE
 ALL "Don't know what item XXX  is at version XXX"

### ISSUE THREAD

**Issue by MeowRay** [Exceptionflug/protocolize#73]
plugin and bungee version: latest
Search "Don't know what item" (216876 hits in 9 files)
	 [Protocolize] Don't know what item 383:0 is at version 340
	 [Protocolize] Don't know what item 449:0 is at version 340
	 [Protocolize] Don't know what item 758:0 is at version 498
	 [Protocolize] Don't know what item 277:0 is at version 498
	 [Protocolize] Don't know what item 589:0 is at version 498
	 [Protocolize] Don't know what item 528:0 is at version 498
	 [Protocolize] Don't know what item 437:0 is at version 340
	 [Protocolize] Don't know what item 251:0 is at version 340
	 [Protocolize] Don't know what item 449:0 is at version 335
	 [Protocolize] Don't know what item 252:0 is at version 340
	 [Protocolize] Don't know what item 588:0 is at version 404
	 [Protocolize] Don't know what item 383:0 is at version 335
	 [Protocolize] Don't know what item 437:0 is at version 335
	 [Protocolize] Don't know what item 447:0 is at version 110
	 [Protocolize] Don't know what item 437:0 is at version 107
	 [Protocolize] Don't know what item 758:0 is at version 578
	 [Protocolize] Don't know what item 188:0 is at version 498
	 [Protocolize] Don't know what item 383:0 is at version 47
	 [Protocolize] Don't know what item 383:0 is at version 110
	 [Protocolize] Don't know what item 433:0 is at version 340
	 [Protocolize] Don't know what item 758:0 is at version 477
	 [Protocolize] Don't know what item 277:0 is at version 477
	 [Protocolize] Don't know what item 575:0 is at version 477
	 [Protocolize] Don't know what item 588:0 is at version 477
	 [Protocolize] Don't know what item 383:0 is at version 316
	 [Protocolize] Don't know what item 575:0 is at version 498
	 [Protocolize] Don't know what item 588:0 is at version 498
	 [Protocolize] Don't know what item 628:0 is at version 498
	 [Protocolize] Don't know what item 626:0 is at version 498
	 [Protocolize] Don't know what item 823:0 is at version 498
	 [Protocolize] Don't know what item 173:0 is at version 498
	 [Protocolize] Don't know what item 819:0 is at version 498
	 [Protocolize] Don't know what item 232:0 is at version 498
	 [Protocolize] Don't know what item 758:0 is at version 490
	 [Protocolize] Don't know what item 122:0 is at version 498
	 [Protocolize] Don't know what item 758:0 is at version 404
	 [Protocolize] Don't know what item 181:0 is at version 498
	 [Protocolize] Don't know what item 517:0 is at version 498
	 [Protocolize] Don't know what item 445:0 is at version 498
	 [Protocolize] Don't know what item 627:0 is at version 498
	 [Protocolize] Don't know what item 854:0 is at version 498
	 [Protocolize] Don't know what item 612:0 is at version 498
	 [Protocolize] Don't know what item 324:0 is at version 498
	 [Protocolize] Don't know what item 108:0 is at version 498
	 [Protocolize] Don't know what item 31:0 is at version 210
	 [Protocolize] Don't know what item 383:0 is at version 338
	 [Protocolize] Don't know what item 212:0 is at version 498
	 [Protocolize] Don't know what item 31:0 is at version 340
	 [Protocolize] Don't know what item 575:0 is at version 573
	 [Protocolize] Don't know what item 277:0 is at version 485
	 [Protocolize] Don't know what item 575:0 is at version 485
	 [Protocolize] Don't know what item 433:0 is at version 110
	 [Protocolize] Don't know what item 437:0 is at version 110
	 [Protocolize] Don't know what item 251:0 is at version 335
	 [Protocolize] Don't know what item 437:0 is at version 316
	 [Protocolize] Don't know what item 444:0 is at version 107
	 [Protocolize] Don't know what item 31:0 is at version 47
 bc\ym1\proxy.log.2 (35975 hits)

**Comment by MeowRay** [comment]
are you ok?

**Comment by Exceptionflug** [comment]
Oh sorry, I've overseen this. I will fix this when I have the time.

**Comment by KotlinFactory** [comment]
Fixed with latest build.
