### ISSUE TITLE
ItemStack doesn't have a way to add enchantments

### ISSUE THREAD

**Issue by DaniFoldi** [Exceptionflug/protocolize#78]
Hi!

I was delighted to see support for custom textures on `PLAYER_HEAD`s, it makes life a lot easier. I was asked to add the option to add enchantments to the displayed inventory, but I didn't find anything that could help me. It is probably doable through the NBTTag system, but without a tutorial I couldn't figure it out. Could you please provide a special method, or a quick demo on how to do it?

Thanks

**Comment by Exceptionflug** [comment]
Duplicate of https://github.com/Exceptionflug/protocolize/issues/7

**Comment by Exceptionflug** [comment]
Hey, please take a look at the issue which I have linked above. There I show a util method to add the glow effect to an ItemStack.

**Comment by DaniFoldi** [comment]
Cheers, I'll close the issue.
