### ISSUE TITLE
Incorrect Item mapping

### ISSUE THREAD

**Issue by Tofuus** [Exceptionflug/protocolize#9]
It looks like the item ids in ItemType are being incorrectly generated. For example ItemType.FILLED_MAP for protocol version 404 should be `613` instead it's `608` which is the id for brown beds

**Comment by Exceptionflug** [comment]
Yeap got that. Will work on a solution asap.

**Comment by Exceptionflug** [comment]
Fixed in https://github.com/Exceptionflug/protocolize/commit/e4e294ae767f9edb59b3e74e76e8622d91922bf6

Release will be available soon.
